# Generated by Django 4.1.7 on 2023-02-26 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_comment_playlist_playlistcontent_user_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['video_id', 'content'], 'verbose_name': 'Коммент', 'verbose_name_plural': 'Комменты'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['user_id', 'name'], 'verbose_name': 'Плейлист', 'verbose_name_plural': 'Плейлисты'},
        ),
        migrations.AlterModelOptions(
            name='playlistcontent',
            options={'ordering': ['playlist_id', 'url'], 'verbose_name': 'Видео плейлиста', 'verbose_name_plural': 'Видео плейлиста'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['login', 'last_name', 'first_name'], 'verbose_name': 'Пользователь/автор', 'verbose_name_plural': 'Пользователи/авторы'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.user', verbose_name='Комментатор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.user', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='playlistcontent',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.playlist', verbose_name='Плейлист'),
        ),
        migrations.AlterField(
            model_name='playlistcontent',
            name='url',
            field=models.CharField(max_length=255, verbose_name='url-адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(upload_to='icons/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=255, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='video',
            name='index',
            field=models.CharField(max_length=255, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(upload_to='previews/', verbose_name='Превьюшка'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.user', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Видео'),
        ),
    ]
